/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject340;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class patientDemographicsForm extends javax.swing.JFrame {

    /**
     * Creates new form patientDemographicsForm
     */
    public patientDemographicsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        txtPtFirstName = new javax.swing.JTextField();
        txtPtLastName = new javax.swing.JTextField();
        txtPtPreviousLastName = new javax.swing.JTextField();
        txtHomeAddress1 = new javax.swing.JTextField();
        txtHomeCity = new javax.swing.JTextField();
        txtHomeState = new javax.swing.JTextField();
        txtHomeZip = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtCitizenship = new javax.swing.JTextField();
        txtPtMobilePhone = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtPtSSN = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtEthnicAssociation = new javax.swing.JTextField();
        txtMaritalStatus = new javax.swing.JTextField();
        txtCurrentPrimaryHCP = new javax.swing.JTextField();
        txtComments = new javax.swing.JTextField();
        txtNextOfKin = new javax.swing.JTextField();
        txtNextOfKinRelationshipToPatient = new javax.swing.JTextField();
        txtEmergencyPhoneNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, 70, -1));

        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 67, -1, -1));

        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 117, -1, -1));

        jLabel4.setText("Previous Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 167, 130, -1));

        jLabel5.setText("Home Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 218, 90, -1));

        jLabel6.setText("Home City");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 267, 80, -1));

        jLabel7.setText("Home State");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 317, 90, -1));

        jLabel8.setText("Home Zip");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 373, 80, -1));

        jLabel9.setText("Country");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 17, 70, -1));

        jLabel10.setText("Citizenship");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 67, -1, -1));

        jLabel11.setText("Mobile Phone");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 117, 90, -1));

        jLabel12.setText("Emergency Phone Number");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 170, -1));

        jLabel13.setText("Email Address");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 167, 100, -1));

        jLabel14.setText("SS#");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 218, 40, -1));

        jLabel15.setText("Date of Birth");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 90, -1));

        jLabel16.setText("Gender");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jLabel17.setText("Ethenic Association");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 17, 120, -1));

        jLabel18.setText("Marital Status");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 67, 110, -1));

        jLabel19.setText("Current Primary HCP");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 117, 140, -1));

        jLabel20.setText("Comments");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 167, 80, -1));

        jLabel21.setText("Next of Kin");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 218, 80, -1));

        jLabel22.setText("Next of Kin Relationship");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 180, -1));
        getContentPane().add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 39, 90, -1));
        getContentPane().add(txtPtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 89, 90, -1));
        getContentPane().add(txtPtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, 90, -1));
        getContentPane().add(txtPtPreviousLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 189, 90, -1));
        getContentPane().add(txtHomeAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 240, 90, -1));
        getContentPane().add(txtHomeCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 289, 90, -1));
        getContentPane().add(txtHomeState, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 339, 90, -1));
        getContentPane().add(txtHomeZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 395, 90, -1));
        getContentPane().add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 39, 90, -1));
        getContentPane().add(txtCitizenship, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 89, 90, -1));
        getContentPane().add(txtPtMobilePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 139, 90, -1));
        getContentPane().add(txtEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 189, 90, -1));
        getContentPane().add(txtPtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 240, 90, -1));
        getContentPane().add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 90, -1));

        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        getContentPane().add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 100, -1));
        getContentPane().add(txtEthnicAssociation, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 39, 100, -1));
        getContentPane().add(txtMaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 89, 100, -1));
        getContentPane().add(txtCurrentPrimaryHCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 139, 100, -1));
        getContentPane().add(txtComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 189, 100, -1));
        getContentPane().add(txtNextOfKin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 100, -1));
        getContentPane().add(txtNextOfKinRelationshipToPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 100, -1));
        getContentPane().add(txtEmergencyPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 100, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 436, 87, 33));

        btnEdit.setText("Edit");
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 436, 84, 33));

        btnNew.setText("New");
        getContentPane().add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 436, 84, 33));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 436, 87, 33));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    String patientID = txtPatientID.getText();
    String ptLastName = txtPtLastName.getText();
    String ptPreviousLastName = txtPtPreviousLastName.getText();
    String ptFirstName = txtPtFirstName.getText();
    String homeAddress1 = txtHomeAddress1.getText();
    String homeCity = txtHomeCity.getText();
    String homeState = txtHomeState.getText();
    String homeZip = txtHomeZip.getText();
    String country = txtCountry.getText();
    String citizenship = txtCitizenship.getText();
    String ptMobilePhone = txtPtMobilePhone.getText();
    String emergencyPhoneNumber = txtEmergencyPhoneNumber.getText();
    String emailAddress = txtEmailAddress.getText();
    String ptSSN = txtPtSSN.getText();
    String dob = txtDOB.getText();
    String gender = txtGender.getText();
    String ethnicAssociation = txtEthnicAssociation.getText();
    String maritalStatus = txtMaritalStatus.getText();
    String currentPrimaryHCP = txtCurrentPrimaryHCP.getText();
    String comments = txtComments.getText();
    String nextOfKin = txtNextOfKin.getText();
    String nextOfKinRelationshipToPatient = txtNextOfKinRelationshipToPatient.getText();

    boolean isSaved = PatientDBUtil.savePatient(
        patientID, ptLastName, ptPreviousLastName, ptFirstName, homeAddress1, homeCity, homeState,
        homeZip, country, citizenship, ptMobilePhone, emergencyPhoneNumber, emailAddress, ptSSN, dob,
        gender, ethnicAssociation, maritalStatus, currentPrimaryHCP, comments, nextOfKin, nextOfKinRelationshipToPatient
    );

     if (isSaved) {
        txtPatientID.setEditable(false);
        txtPtLastName.setEditable(false);
        txtPtPreviousLastName.setEditable(false);
        txtPtFirstName.setEditable(false);
        txtHomeAddress1.setEditable(false);
        txtHomeCity.setEditable(false);
        txtHomeState.setEditable(false);
        txtHomeZip.setEditable(false);
        txtCountry.setEditable(false);
        txtCitizenship.setEditable(false);
        txtPtMobilePhone.setEditable(false);
        txtEmergencyPhoneNumber.setEditable(false);
        txtEmailAddress.setEditable(false);
        txtPtSSN.setEditable(false);
        txtDOB.setEditable(false);
        txtGender.setEditable(false);
        txtEthnicAssociation.setEditable(false);
        txtMaritalStatus.setEditable(false);
        txtCurrentPrimaryHCP.setEditable(false);
        txtComments.setEditable(false);
        txtNextOfKin.setEditable(false);
        txtNextOfKinRelationshipToPatient.setEditable(false);
        
    } else {
        JOptionPane.showMessageDialog(this, "There was an issue saving the patient. Please try again.");
    }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

   
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientDemographicsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCitizenship;
    private javax.swing.JTextField txtComments;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtCurrentPrimaryHCP;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtEmergencyPhoneNumber;
    private javax.swing.JTextField txtEthnicAssociation;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHomeAddress1;
    private javax.swing.JTextField txtHomeCity;
    private javax.swing.JTextField txtHomeState;
    private javax.swing.JTextField txtHomeZip;
    private javax.swing.JTextField txtMaritalStatus;
    private javax.swing.JTextField txtNextOfKin;
    private javax.swing.JTextField txtNextOfKinRelationshipToPatient;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPtFirstName;
    private javax.swing.JTextField txtPtLastName;
    private javax.swing.JTextField txtPtMobilePhone;
    private javax.swing.JTextField txtPtPreviousLastName;
    private javax.swing.JTextField txtPtSSN;
    // End of variables declaration//GEN-END:variables
}
